import { AccountEntity, DetailAccountEntity } from './accounts';
import { KeyTokenEntity, LoginHistoryEntity, RoleEntity, SessionEntity } from './auth';
import {
   CategoryEntity,
   CourseContentEntity,
   CourseEntity,
   CourseProgressEntity,
   EnrollmentEntity,
   ProgresDetailsEntity,
   CourseModuleEntity,
   CourseLessionEntity,
   AssignmentEntity,
   CertificateEntity,
   QuizQuestionEntity,
   ReviewEntity,
   SubmissionEntity,
   CouponEntity,
   TagEntity,
} from './courses';
import { InteractionEntity } from './courses/interaction.entity';

export const entities = [
   AccountEntity,
   RoleEntity,
   SessionEntity,
   KeyTokenEntity,
   LoginHistoryEntity,
   DetailAccountEntity,
   EnrollmentEntity,
   CourseEntity,
   CategoryEntity,
   CourseProgressEntity,
   ProgresDetailsEntity,
   CourseContentEntity,
   CourseModuleEntity,
   CourseLessionEntity,
   ReviewEntity,
   AssignmentEntity,
   SubmissionEntity,
   QuizQuestionEntity,
   CertificateEntity,
   CouponEntity,
   TagEntity,
   InteractionEntity,
];
